{{- if .Values.puppeteer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsshub.puppeteer.fullname" . }}
  labels:
    {{- include "rsshub.puppeteer.labels" . | nindent 4 }}
    {{- with .Values.puppeteer.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.puppeteer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.puppeteer.servicePort }}
      targetPort: {{ .Values.puppeteer.containerPort }}
      protocol: TCP
      name: websocket
  selector:
    {{- include "rsshub.puppeteer.selectorLabels" . | nindent 4 }}
{{- end }}